apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.19.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: medblocks-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Automatically redirects to https if certificates are obtained
  displayName: knative-https-redirect
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - knative
  - https
  links:
  - name: Medblocks Operator
    url: https://medblocks-operator.domain
  maturity: alpha
  provider:
    name: Sidharth Ramesh
  version: 0.0.1
